const fs = require('fs');
const path = require('path');

const targetFile = path.join(__dirname, 'src/pages/flashcards/FlashSpace.tsx');
let content = fs.readFileSync(targetFile, 'utf8');
content = content.replace(/\r\n/g, '\n');

// 1. Update board generation logic
const targetBoardGen = `              module: 'Pediatrics',
              system: chapter,`;
const replaceBoardGen = `              module: chapter.startsWith('تحديدات الاطفال') ? 'تحديدات الاطفال' : 'Pediatrics',
              system: chapter.startsWith('تحديدات الاطفال') ? chapter.replace('تحديدات الاطفال - ', '').replace('تحديدات الاطفال', 'All') : chapter,`;

if (content.includes(targetBoardGen)) {
    content = content.replace(targetBoardGen, replaceBoardGen);
}

// 2. Add image to module card and remove old gradient logic if possible
const targetModuleCardContent = `{/* Gradient Glow */}
                      <div className="absolute top-0 right-0 w-40 h-40 opacity-10 group-hover:opacity-30 transition-opacity duration-500 blur-3xl rounded-full" style={{background: mod === 'تحديدات الاطفال' ? '#f97316' : '#6366f1', transform: 'translate(40%, -40%)'}} />`;

const replaceModuleCardContent = `{/* Image for Tahdedat Module */}
                      {mod === 'تحديدات الاطفال' && (
                        <div className="absolute inset-0 z-0">
                          <img src="/assets/chapters/418309698_0f732299-96c6-4f6d-8f13-82ad46c35262.jpg" alt={mod} className="w-full h-full object-cover opacity-50 mix-blend-overlay group-hover:opacity-70 transition-opacity duration-500" />
                          <div className="absolute inset-0 bg-gradient-to-t from-slate-900/90 via-slate-900/40 to-transparent" />
                        </div>
                      )}
                      {/* Gradient Glow */}
                      <div className="absolute top-0 right-0 w-40 h-40 opacity-10 group-hover:opacity-30 transition-opacity duration-500 blur-3xl rounded-full" style={{background: mod === 'تحديدات الاطفال' ? '#f97316' : '#6366f1', transform: 'translate(40%, -40%)'}} />`;

if (content.includes(targetModuleCardContent)) {
    content = content.replace(targetModuleCardContent, replaceModuleCardContent);
}

// 3. Clean up the system card background image logic
const targetSysBgLogic = `{(SYSTEM_BGS[sys] || (sys.startsWith('تحديدات الاطفال') ? '/assets/chapters/418309698_0f732299-96c6-4f6d-8f13-82ad46c35262.jpg' : null)) && (
                          <div className="absolute inset-0 z-0">
                            <img src={SYSTEM_BGS[sys] || (sys.startsWith('تحديدات الاطفال') ? '/assets/chapters/418309698_0f732299-96c6-4f6d-8f13-82ad46c35262.jpg' : '')} alt={sys} className="w-full h-full object-cover opacity-40 group-hover:opacity-70 transition-all duration-500 mix-blend-overlay" />`;

const replaceSysBgLogic = `{SYSTEM_BGS[sys] && (
                          <div className="absolute inset-0 z-0">
                            <img src={SYSTEM_BGS[sys]} alt={sys} className="w-full h-full object-cover opacity-40 group-hover:opacity-70 transition-all duration-500 mix-blend-overlay" />`;

if (content.includes(targetSysBgLogic)) {
    content = content.replace(targetSysBgLogic, replaceSysBgLogic);
} else {
    // If it was already cleaned or different
}

// 4. Update the sorting of modules to put 'تحديدات الاطفال' first
// Wait, modules is generated by Array.from(new Set(finalBoards.map(b => b.module)))
const targetModules = `const mods = Array.from(new Set(finalBoards.map(b => b.module))).filter(Boolean);`;
const replaceModules = `const mods = Array.from(new Set(finalBoards.map(b => b.module))).filter(Boolean).sort((a, b) => {
          if (a === 'تحديدات الاطفال') return -1;
          if (b === 'تحديدات الاطفال') return 1;
          return a.localeCompare(b);
        });`;

if (content.includes(targetModules)) {
    content = content.replace(targetModules, replaceModules);
}

fs.writeFileSync(targetFile, content, 'utf8');
console.log('Refactor completed successfully!');
